// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $devtools_demos_proxy from "./routes/devtools_demos_proxy.ts";
import * as $emoji_index from "./routes/emoji/index.tsx";
import * as $feed_fetch from "./routes/feed/fetch.tsx";
import * as $index from "./routes/index.tsx";
import * as $ipsum from "./routes/ipsum.tsx";
import * as $lorem from "./routes/lorem.tsx";
import * as $og from "./routes/og.jsx";
import * as $prefetch_num_ from "./routes/prefetch/[num].tsx";
import * as $prefetch_index from "./routes/prefetch/index.tsx";
import * as $prerender_all_the_pre from "./routes/prerender/all-the-pre.tsx";
import * as $prerender_index from "./routes/prerender/index.tsx";
import * as $prerender_mega from "./routes/prerender/mega.tsx";
import * as $prerender_noprerender_target from "./routes/prerender/noprerender-target.tsx";
import * as $prerender_nostate_prefetch from "./routes/prerender/nostate-prefetch.tsx";
import * as $prerender_prerender_target from "./routes/prerender/prerender-target.tsx";
import * as $sleep from "./routes/sleep.tsx";
import * as $ssml_index from "./routes/ssml/index.tsx";
import * as $utils_blurhash from "./routes/utils/blurhash.tsx";
import * as $utils_nanoid_json from "./routes/utils/nanoid.json.tsx";
import * as $utils_nanoid from "./routes/utils/nanoid.tsx";
import * as $utils_sha1 from "./routes/utils/sha1.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/devtools_demos_proxy.ts": $devtools_demos_proxy,
    "./routes/emoji/index.tsx": $emoji_index,
    "./routes/feed/fetch.tsx": $feed_fetch,
    "./routes/index.tsx": $index,
    "./routes/ipsum.tsx": $ipsum,
    "./routes/lorem.tsx": $lorem,
    "./routes/og.jsx": $og,
    "./routes/prefetch/[num].tsx": $prefetch_num_,
    "./routes/prefetch/index.tsx": $prefetch_index,
    "./routes/prerender/all-the-pre.tsx": $prerender_all_the_pre,
    "./routes/prerender/index.tsx": $prerender_index,
    "./routes/prerender/mega.tsx": $prerender_mega,
    "./routes/prerender/noprerender-target.tsx": $prerender_noprerender_target,
    "./routes/prerender/nostate-prefetch.tsx": $prerender_nostate_prefetch,
    "./routes/prerender/prerender-target.tsx": $prerender_prerender_target,
    "./routes/sleep.tsx": $sleep,
    "./routes/ssml/index.tsx": $ssml_index,
    "./routes/utils/blurhash.tsx": $utils_blurhash,
    "./routes/utils/nanoid.json.tsx": $utils_nanoid_json,
    "./routes/utils/nanoid.tsx": $utils_nanoid,
    "./routes/utils/sha1.tsx": $utils_sha1,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
