// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/devtools_demos_proxy.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/og.jsx";
import * as $4 from "./routes/prefetch/[num].tsx";
import * as $5 from "./routes/prefetch/index.tsx";
import * as $6 from "./routes/utils/nanoid.json.tsx";
import * as $7 from "./routes/utils/nanoid.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/devtools_demos_proxy.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/og.jsx": $3,
    "./routes/prefetch/[num].tsx": $4,
    "./routes/prefetch/index.tsx": $5,
    "./routes/utils/nanoid.json.tsx": $6,
    "./routes/utils/nanoid.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
